config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/survey', to: 'survey#one'
  get '/survey/2', to: 'survey#two'
  get '/survey/3', to: 'survey#three'
  get '/survey/results', to: 'survey#results'

  root to: 'index#index'
  get '/candidates', to: 'index#candidates'
  get '/candidates/carmen', to: 'index#carmen'
  get '/candidates/muffy', to: 'index#muffy'
  get '/candidates/steven', to: 'index#steven'
  get '/ballot', to: 'index#ballot'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def ballot
  end

  def index
  end

  def candidates
  end

  def carmen
  end

  def muffy
  end

  def steven
  end
end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
  def one
  end
  def two
  end
  def three
  end
  def results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/index/ballot.html.haml
%br
= image_tag  "sample-ballot.png", :class => "img-responsive center-block"

app/views/index/candidates.html.haml
%ul
  %li
    = link_to 'Meet Steven', '/candidates/steven'
  %li
    = link_to 'Meet Carmen', '/candidates/carmen'
  %li
    = link_to 'Meet Muffy', '/candidates/muffy'

app/views/index/carmen.html.haml
%h2.text-center
  Carmen Liu(3rd Party)

.candidate-img
  = image_tag('carmen.jpg', class:'img-responsive center-block', size:'200x120')

.col-md-5
.col-md-6
  %ul
    %li
      MIT Grad
    %li
      Software Developer
    %li
      Hates Hotdogs
    %li
      Meh on Chocolate
    %li
      Hates Dogs

.col-md-1

app/views/index/index.html.haml
.text-center
  %br
  = image_tag('voicesvotetag.png', size: "800x200", class: 'center-block img-responsive')
  %hr
  .container
    .row
      .col-sm-4
        = link_to 'Candidate Match <i class="glyphicon glyphicon-arrow-right"></i>'.html_safe, '/survey', class: 'btn btn-lg btn-primary'
      .col-sm-4
        = link_to 'Candidate Information <i class="glyphicon glyphicon-arrow-right"></i>'.html_safe, '/candidates', class: 'btn btn-lg btn-primary'
      .col-sm-4
        = link_to 'Ballot Info <i class="glyphicon glyphicon-arrow-right"></i>'.html_safe, '/ballot', class: 'btn btn-lg btn-primary'
%br
%br
%br
%hr
.embed-responsive.embed-responsive-16by9
  <iframe width="560" height="315" src="https://www.youtube.com/embed/ODETODyDA6A" frameborder="0" allowfullscreen></iframe>

app/views/index/muffy.html.haml
%h2.text-center
  Muffy Weiler(D)

.candidate-img
  = image_tag('muffy.jpg', class:'img-responsive center-block', size:'200x120')

.col-md-5
.col-md-6
  %ul
    %li
      Harvard Lawyer
    %li
      Governor of MN
    %li
      Pro Hotdogs
    %li
      Against Chocolate
    %li
      Loves Dogs

.col-md-1

app/views/index/steven.html.haml
%h2.text-center
  Steven Mark(D)

.candidate-img
  = image_tag('stevenmark.jpg', class:'img-responsive center-block', size:'200x120')

.col-md-5
.col-md-6
  %ul
    %li
      GED
    %li
      Inside Sales
    %li
      Chicago Dogs or BUST
    %li
      Loves Chocolate
    %li
      Has a Dog
.col-md-1

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title VoicesAndVoting
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container.banner
      .row
        .col-xs-3
          = link_to image_tag( 'logo.png', size: "160x160", class: 'img-responsive'), '/'
        .col-xs-9
          = image_tag('voicesvoting.png', size: "600x200", class: 'img-responsive')      
    .container
      = yield

app/views/survey/one.html.haml
%h1.text-center
  Candidate Match Questionaire
%hr
%h2
  Immigration

%ul
  %li
    = link_to 'Build a wall', survey_2_path(one: 'less')
  %li
    = link_to 'Everyone is welcome', survey_2_path(one: 'more')

app/views/survey/results.html.haml
%h1.text-center
  Results
%hr
.text-center
  %h2
    Candidate Match
  %h3
    You match with
    Muffy Weiler (D)
  = image_tag('muffy.jpg', size: '400x400', class: 'center-block img-responsive')
  %h3 
    You agree on
    
  = "#{params[:one]} immigration".humanize
  %br
  = "#{params[:two]} taxes".humanize
  %br
  = "#{params[:three]} guns".humanize


%hr
%br
= link_to 'Learn More', '#'

app/views/survey/three.html.haml
%h1.text-center
  Candidate Match Questionaire
%hr
%h2
  Guns

%ul
  %li
    = link_to 'More Gun Control', survey_results_path(one: params[:one], two: params[:two], three: 'more')
  %li
    = link_to 'Less Gun Control', survey_results_path(one: params[:one], two: params[:two], three: 'less') 

app/views/survey/two.html.haml
%h1.text-center
  Candidate Match Questionaire
%hr
%h2
  Taxes

%ul
  %li
    = link_to 'More Taxes', survey_3_path(one: params[:one], two: 'more')
  %li
    = link_to 'Less Taxes', survey_3_path(one: params[:one], two: 'less')